version: '3'

services:

    # NGINX
    nginx:
        container_name: "${APP_NAME}-nginx"
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - '${HTTP_PORT:-80}:80'
        volumes:
            - ./logs:/var/log/nginx
            - ./src:/var/www
        links:
            - php
        depends_on:
            - php
        networks:
            - localnet

    # PHP
    php:
        container_name: "${APP_NAME}-php"
        build: ./docker/php
        links:
            - mysql
        volumes:
            - ./src:/var/www
            - ./logs:/var/log/php
        networks:
            - localnet

    # MYSQL
    mysql:
        container_name: "${APP_NAME}-mysql"
        build: ./docker/mysql
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - ./logs:/var/log/mysql
            - ./db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        command: mysqld --sql-mode=""
        networks:
            - localnet

    # PHPMYADMIN
    phpmyadmin:
        container_name: "${APP_NAME}-phpmyadmin"
        image: phpmyadmin:latest
        links:
            - mysql
        ports:
            - '${PMA_PORT:-8082}:80'
        environment:
            MYSQL_USERNAME: "${DB_USER}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: mysql
        depends_on:
            - mysql
        networks:
            - localnet

# INTERNET
networks:
    localnet:
        driver: bridge

volumes:
    local-mysql:
        driver: local